[package]
name = "aht20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
defmt = ["dep:defmt"]

[dependencies]
crc = "3.0.1"
embedded-hal = "0.2.7"
defmt = { version = "0.3.2", optional = true }
